name: Publish to PyPI

on:
  release:
    types: [released, published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: zanecodes/python-publish/build-wheel@v1

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: zanecodes/python-publish/build-sdist@v1

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: zanecodes/python-publish/publish@v1
        with:
          repository_url: https://test.pypi.org/legacy/
